// Copyright 2023 linlin012 (@linlin012)
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

#undef PERMISSIVE_HOLD
#undef PREVENT_STUCK_MODIFIERS

#define TAPPING_TERM 200

#define CAPS_LOCK_INDEX 28
#define WIN_MOD_INDEX 16
#define MAC_MOD_INDEX 17
#define AW20216S_SDB_PIN A4
#define TAPPING_TERM_PER_KEY

#define AW20216S_CS_PIN_1 B12
#define AW20216S_EN_PIN_1 A4

#define ENABLE_RGB_MATRIX_PIXEL_FRACTAL
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_NEXUS
